name = "Card"
description = "Displays a card with header, content, and footer."

[[examples]]
name = "card"

[[references]]
name = "Card"
description = "Contains all the parts of a card."
extra = """Implements <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes">global</a> \
attributes."""
attrs = []

[[references]]
name = "CardContent"
description = "Contains the content displayed in the card body."
extra = """Implements <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes">global</a> \
attributes."""
attrs = []

[[references]]
name = "CardDescription"
description = "A summary that describes the card content."
extra = """Implements <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes">global</a> \
attributes."""
attrs = []

[[references]]
name = "CardFooter"
description = "Contains card footer content."
extra = """Implements <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes">global</a> \
attributes."""
attrs = []

[[references]]
name = "CardHeader"
description = "Renders at the top of the card. Contains the card title and card description."
extra = """Implements <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes">global</a> \
attributes."""
attrs = []

[[references]]
name = "CardTitle"
description = "The title of the card."
extra = """Implements <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes">global</a> \
attributes."""
attrs = []
