name = "Progress"
description = """Displays an indicator showing the completion progress of a task, typically \
displayed as a progress bar."""

[[examples]]
name = "progress"

[[references]]
name = "Progress"
description = "Displays progress."
extra = """Implements <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes">global</a> \
attributes."""
attrs = [
  { attr = "max", attr_type = "usize", default = "100", description = """The value that \
    represents 100%, or full.""" },
  { attr = "value", attr_type = "usize", default = "0", description = """The current progress \
    value to be rendered.""" },
]
