name = "Field"
description = """Combine labels, controls, and help text to compose accessible form fields and \
grouped inputs."""

[[examples]]
name = "field"

[[examples]]
name = "field input"
title = "Input"

[[examples]]
name = "field textarea"
title = "Textarea"

[[examples]]
name = "field select"
title = "Select"

[[examples]]
name = "field slider"
title = "Slider"

[[examples]]
name = "field set"
title = "Fieldset"

[[examples]]
name = "field checkbox"
title = "Checkbox"

[[examples]]
name = "field radio"
title = "Radio"

[[examples]]
name = "field switch"
title = "Switch"

[[examples]]
name = "field choice card"
title = "Choice Card"
description = """Wrap Field components inside FieldLabel to create selectable field groups. This \
works with Radio, Checkbox and Switch components."""

[[examples]]
name = "field group"
title = "Field Group"
description = "Stack Field components with FieldGroup. Add FieldSeparator to divide them."

[[examples]]
name = "field responsive layout"
title = "Responsive Layout"

[[references]]
name = "Field"
description = "A form input field."
extra = """Implements <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes">global</a> \
attributes."""
attrs = [
  { attr = "orientation", attr_type = "String", default = "\"vertical\"", description = """Sets \
    the display orientation. Accepted values: \"vertical\" | \"horizontal\" | \"responsive\".""" },
]

[[references]]
name = "FieldContent"
description = "Contains field content."
extra = """Implements <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes">global</a> \
attributes."""
attrs = []

[[references]]
name = "FieldDescription"
description = "Contains a description of content for the input in a field."
extra = """Implements <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes">global</a> \
attributes."""
attrs = []

[[references]]
name = "FieldError"
description = "An error message related to field input."
extra = """Implements <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes">global</a> \
attributes."""
attrs = []

[[references]]
name = "FieldGroup"
description = "Groups together related input fields."
extra = """Implements <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes">global</a> \
attributes."""
attrs = []

[[references]]
name = "FieldLabel"
description = "The label associated with an input."
extra = """Implements <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes">global</a> \
attributes."""
attrs = [
  { attr = "label_for", attr_type = "String", default = """""""", description = """Renamed \
    <label> `for` attribute to avoid name collisions.""" },
]

[[references]]
name = "FieldLegend"
description = "A title for a FieldSet."
extra = """Implements <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes">global</a> \
attributes."""
attrs = [
  { attr = "variant", attr_type = "String", default = "\"legend\"", description = """Set the \
    display style of the FieldLegend. Accepted values: \"label\" | \"legend\".""" },
]

[[references]]
name = "FieldSet"
description = "Contains a set of related input fields or groups of fields."
extra = """Implements <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes">global</a> \
and <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/fieldset#attributes">fieldset</a> \
attributes."""
attrs = []

[[references]]
name = "FieldTitle"
description = "A title associated with a field."
extra = """Implements <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes">global</a> \
attributes."""
attrs = []
