name = "Checkbox"
description = "A control that allows the user to toggle between checked and not checked."

[[examples]]
name = "checkbox"

[[examples]]
name = "subtext"

[[examples]]
name = "form"

[[examples]]
name = "group"
title = "Checkbox Group"

[[references]]
name = "Checkbox"
description = "A control that allows the user to toggle between checked and not checked."
extra = """Implements <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes">global</a>, \
<a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/input#attributes">input</a>, \
and <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/input/checkbox#additional_attributes">checkbox</a> \
attributes."""
attrs = [
  { attr = "checked", attr_type = "RwSignal<bool>", default = "false", description = """A \
    reactive signal coupled to the checkbox's checked value.""" },
]

[[references]]
name = "CheckboxGroup"
description = "Contains all the parts of a checkbox group."
extra = """Implements <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes">global</a> \
and <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/fieldset#attributes">fieldset</a> \
attributes."""
attrs = [
  { attr = "invalid", attr_type = "RwSignal<bool>", default = "false", description = """A \
    reactive signal that toggles whether all the children Checkboxes appear invalid or not.""" },
  { attr = "value", attr_type = "RwSignal<Vec<String>>", default = "[]", description = """A \
    dynamic list of all the values of checked children Checkboxes.""" },
]
