name = "Skeleton"
description = "Use to show a placeholder while content is loading."

[[examples]]
name = "skeleton"

[[examples]]
name = "skeleton card"
title = "Card"

[[references]]
name = "Skeleton"
description = "Creates a skeleton used to show a placeholder while content is loading."
extra = """Implements <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes">global</a> \
attributes."""
attrs = []
