name = "Empty"
description = "Use the Empty component to display an empty state."

[[examples]]
name = "empty"

[[examples]]
name = "empty outline"
title = "Outline"
description = "Use the border utility class to create an outline empty state."

[[examples]]
name = "empty background"
title = "Background"
description = "Use the bg-* and bg-gradient-* utilities to add a background to the empty state."

[[examples]]
name = "empty avatar"
title = "Avatar"
description = "Use the EmptyMedia component to display an avatar in the empty state."

[[examples]]
name = "empty avatar group"
title = "Avatar Group"
description = "Use the EmptyMedia component to display an avatar group in the empty state."

[[references]]
name = "Empty"
description = "Displays progress."
extra = """Implements <a class="singlestage-link" \
href="https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Global_attributes">global</a> \
attributes."""
attrs = [
  { attr = "max", attr_type = "usize", default = "100", description = """The value that \
    represents 100%, or full.""" },
  { attr = "value", attr_type = "usize", default = "0", description = """The current progress \
    value to be rendered.""" },
]
